a <- (1+3)==2; // false
b <- true;
c <- -123;
e <- (1+2+3) + c + (3*1/10);
if (a==b) <<
		c <- "ok";
>> else <<
		c <- "not_ok";
>>
boolVal <- !false;
c <-> e;
a <-> c;

fn add[x, y] <<
		return x+y;
>>

first <- 100;
second <- 200;

fnval <- add(first+(5-3)*second, 1000);

fn arrayAccess[] <<
		local z <- [1,3,4];
		return z@1 + z@2;
>>

zz <- arrayAccess();
arr <- [100,200];
sum <- arr@0 + arr@1;

array <- [1,2,3,4];
if (array@0 == 1) <<
		result <- "equals 1";
>>
